// UI copy added or reworded by the redesign; merged over the base translations in i18n.js.
export const strings = {
  en: {
    // shell
    collection: 'Collection',
    results: 'Results',
    cases: 'Tests',
    noCollection: 'No collection open',
    openShort: 'Open',
    closeShort: 'Close',
    closeCollection: 'Close this collection',
    newShort: 'New',
    searchTests: 'Search tests',
    noMatches: 'Nothing matches.',
    empty: 'No tests yet.',
    notRun: 'Not run yet',
    back: 'Back',
    copied: 'Copied to clipboard',
    folderMissing: 'That folder no longer contains a collection.',
    discardConfirm: 'You have unsaved changes. Discard them?',
    unsavedChanges: 'Unsaved changes',
    discard: 'Discard',
    saveChanges: 'Save changes',
    saved: 'Saved',
    deleted: 'Deleted',
    // shared steps
    sharedTab: 'Shared steps',
    sharedSteps: 'Shared steps',
    sharedBadge: 'SHARED',
    newShared: 'New shared steps',
    noSharedTitle: 'No shared steps yet',
    noSharedDescription:
      'Steps that many tests need first, like getting an auth token or an id from the database, can be written once here and reused.',
    sharedHint:
      'Add a shared group to any test with “Use shared steps”. Variables it saves are available to the steps that follow.',
    sharedNamePlaceholder: 'Name these shared steps, e.g. Get auth token',
    nameRequiredShared: 'A name is needed before saving.',
    sharedFileHint: 'This file name stays fixed, because tests refer to it.',
    sharedStepButton: 'Use shared steps',
    sharedStepButtonHint: 'Run a group of shared steps first',
    noSharedYet: 'Create shared steps first (Collection → Shared steps)',
    chooseShared: 'Choose shared steps…',
    sharedMissing: 'These shared steps no longer exist.',
    stepsShort: 'steps',
    stepOne: 'step',
    runMode: 'When to run',
    runsOnce: 'Once per run',
    runsEach: 'In every test',
    runsOnceHint:
      'Runs a single time per run (for example one login for all tests). Its result is reused, and it cannot depend on a test’s own variables.',
    runsEachHint: 'Runs again inside every test that uses it, with that test’s variables.',
    providesHint: 'A variable these steps save',
    run: 'Run all',
    // welcome & setup
    welcomeTitle: 'API tests, without the code',
    welcomeSub:
      'Describe requests and checks in a visual builder. Everything is stored as readable files you can keep in Git and run in CI.',
    open: 'Open collection',
    openDescription: 'Pick a folder that already contains a collection.',
    createNew: 'New collection',
    emptyCollectionDescription: 'Start from scratch and add tests as you go.',
    importOpenApi: 'Import OpenAPI',
    importOpenApiShort: 'Generate a starter test for every endpoint of an API.',
    recent: 'Recent collections',
    folderWithoutCollection: 'This folder has no collection yet.',
    createHere: 'Create collection here',
    setupTitle: 'New collection',
    setupSub: 'A collection is a folder of tests plus shared variables, connections and secrets.',
    chooseFolderHint: 'You will choose where to save it next.',
    emptyCollectionTitle: 'Empty collection',
    importOpenApiTitle: 'Import from OpenAPI',
    importOpenApiDescription: 'Swagger / OpenAPI document URL',
    // collection page
    overviewTitle: 'Collection',
    overviewSub: 'Manage tests and the variables, connections and secrets they share.',
    newCase: 'New test',
    globals: 'Variables',
    connections: 'Connections',
    secrets: 'Secrets',
    noTestsTitle: 'No tests yet',
    noTestsDescription:
      'Create your first test, or import one for every endpoint from an OpenAPI document.',
    variablesHint:
      'Use a variable anywhere as {{name}}. Names may contain letters and underscores only.',
    noVariablesTitle: 'No variables',
    noVariablesDescription: 'Variables keep values such as base URLs in one place.',
    connectionsHint:
      'Database connections used by SQL steps. Put passwords in secrets: {{secret.name}}.',
    noConnectionsTitle: 'No connections',
    noConnectionsDescription: 'Add a database connection to run SQL steps.',
    noSecretsTitle: 'No secrets',
    noSecretsDescription: 'Secrets keep passwords and tokens out of your files.',
    addVariable: 'Add variable',
    addConnection: 'Add connection',
    addSecret: 'Add secret',
    name: 'Name',
    value: 'Value',
    provider: 'Provider',
    connectionString: 'Connection string',
    remove: 'Remove',
    secretsHint:
      'Reference a secret anywhere as {{secret.name}}. Only where it comes from is saved in the collection file, never the value.',
    environmentHint:
      'An environment override replaces the default source when that environment is selected next to Run.',
    secretName: 'name',
    secretDefaultSource: 'Default source',
    secretLocalNote: 'Value is stored on this machine',
    secretValue: 'Enter value (write-only)',
    secretStored: 'Stored securely',
    secretSetValue: 'Save value',
    secretKeyPlaceholder: 'key',
    copySnippet: 'Copy reference',
    addEnvironment: 'Add environment override',
    environmentName: 'environment, e.g. ci',
    environment: 'Environment',
    environmentDefault: 'default',
    // builder
    testNamePlaceholder: 'Name this test',
    descriptionPlaceholder: 'Add a short description (optional)',
    testName: 'Test name',
    description: 'Description',
    endpoint: 'Endpoint',
    endpointHint: 'Used to group this test in the sidebar and in results.',
    fileHint:
      'The file name follows the test name automatically, unless you have renamed the file yourself.',
    newFileHint: 'The file name is chosen from the test name when you save.',
    nameAndEndpointRequired: 'A name and an endpoint are needed before saving.',
    method: 'Method',
    steps: 'Steps',
    expandAll: 'Expand all',
    collapseAll: 'Collapse all',
    noSteps: 'Add a request or SQL step to get started.',
    requestStep: 'Request step',
    dbStep: 'Database step',
    untitledStep: 'Untitled step',
    moveUp: 'Move up',
    moveDown: 'Move down',
    delete: 'Delete',
    saveTest: 'Save test',
    saveAs: 'Save result as',
    saveAsHint: 'Optional. Use the result in later steps.',
    resultName: 'todo',
    url: 'URL',
    queryParamsShort: 'Params',
    headersShort: 'Headers',
    bodyShort: 'Body',
    addQueryParameter: 'Add parameter',
    addHeader: 'Add header',
    connection: 'Connection',
    chooseConnection: 'Choose a connection…',
    noConnectionsYet: 'Add connections in the collection first',
    sql: 'SQL query',
    assertions: 'Assertions',
    noAssertions: 'No assertions yet. Add one to check the response.',
    addAssertion: 'Add assertion',
    assertionCheck: 'Check',
    assertionValue: 'status, body.items.0.name …',
    sourceResult: 'step result',
    sourceSaved: 'saved result',
    sourceVariable: 'variable',
    aggregation: 'Aggregation',
    aggregationNone: 'none',
    aggregationHint:
      'Compare a computed value instead of the value itself: count of items, or sum / avg / min / max of numbers. Use * in the path to collect a field from every item, e.g. body.items.*.price',
    operator: 'Operator',
    expected: 'Expected',
    operatorLabels: {
      '==': '= equals',
      '!=': '≠ not equals',
      '>': '> greater than',
      '>=': '≥ at least',
      '<': '< less than',
      '<=': '≤ at most',
      approx: '≈ approximately',
      contains: 'contains',
      not_contains: 'does not contain',
      starts_with: 'starts with',
      ends_with: 'ends with',
      matches: 'matches regex',
      in: 'is one of',
      not_in: 'is not one of',
      exists: 'has a value',
      not_exists: 'has no value',
      is_null: 'is null',
      is_missing: 'is missing',
      is_empty: 'is empty',
      is_not_empty: 'is not empty',
      is_type: 'has type',
    },
    opGroupCompare: 'Compare',
    opGroupText: 'Text',
    opGroupList: 'List',
    opGroupPresence: 'Presence and type',
    valueTypes: {
      string: 'text',
      number: 'number',
      boolean: 'true / false',
      array: 'list',
      object: 'object',
      null: 'null',
    },
    expectedListPlaceholder: '200, 201, 204',
    expectedRegexPlaceholder: '^[0-9a-f]{8}$',
    assertionOptions: 'Comparison options',
    caseSensitive: 'Case sensitive',
    caseSensitiveHint:
      'Distinguish upper and lower case in text comparisons (default: ignore case).',
    strictTypes: 'Strict types',
    strictTypesHint: 'No conversion between types: the text "200" is not equal to the number 200.',
    tolerance: 'Tolerance ±',
    yaml: 'Generated YAML',
    // results
    running: 'Running tests…',
    runningSub: 'Requests and queries are being executed.',
    noRunTitle: 'No results yet',
    noRun: 'Run the collection to see what passed and why something failed.',
    runAgain: 'Run again',
    runFailedTitle: 'The run could not start',
    allPassed: 'All tests passed',
    someErrors: '{errors} of {total} tests could not be evaluated',
    failedAndErrors: '{failed} failed, {errors} could not be evaluated',
    couldNotEvaluate: 'Could not evaluate this check',
    couldNotEvaluatePlural: 'Could not evaluate',
    stepCouldNotRun: 'This step could not run',
    errorsShort: 'Errors',
    errorsHint:
      'These are problems with the test itself (a typo in an operator or source, an unresolved variable, an unreachable server), not failed checks.',
    someFailed: '{failed} of {total} tests failed',
    total: 'Total',
    passed: 'Passed',
    failed: 'Failed',
    success: 'Success rate',
    testResults: 'Test results',
    filter: 'Filter results',
    filterAll: 'All',
    expectedLabel: 'Expected',
    actualLabel: 'Actual',
    status: 'Status',
    rows: 'rows',
    raw: 'Raw report',
    noOutput: 'No output.',
    emptyOutput: 'No tests were run.',
    // run scope, progress and cancel
    runTest: 'Run this test',
    runTestSaveFirst: 'Save the test first',
    runFailedAgain: 'Re-run failed',
    cancelRun: 'Cancel',
    progressCount: '{done} of {total} tests finished',
    runCancelled: 'Run cancelled',
    runCancelledSub: '{done} of {total} tests finished before it was cancelled.',
    ranSubset: 'Ran {count} of the collection’s tests',
    // step preview
    send: 'Send',
    sendHint: 'Run the steps up to this one and show what it received',
    sending: 'Sending…',
    response: 'Response',
    responseHeaders: 'Headers',
    responseTruncated: 'The response is long; only its beginning is shown.',
    rowsShown: 'Showing {shown} of {total} rows',
    clickToAssert: 'Click a value to add a check for it.',
    countCheck: 'Add a count check',
    stoppedEarlier: 'Stopped at step {step} ({name}), before reaching this one.',
    noResponse: 'This step received no response.',
    closePreview: 'Close',
    bodyNotJson:
      'This body is not valid JSON ({error}), so it is sent as text/plain. In JSON, keys and text need double quotes: {"title": "foo"}.',
    bodyNotJsonDeclared:
      'This body is not valid JSON ({error}), but the Content-Type header says JSON, so the server will probably reject it. In JSON, keys and text need double quotes: {"title": "foo"}.',
    cloneTest: 'Clone',
    cloneTestHint: 'Make a copy of this test to use as a starting point for a variation',
    cloned: 'Test cloned',
    copyName: '{name} (copy)',
    copyNameN: '{name} (copy {n})',
    sentRequest: 'Request sent',
    sentSql: 'SQL run',
    noRequestBody: 'No body was sent.',
    copyCurl: 'Copy as cURL',
    copyCurlHint: 'Copies the request as a curl command. Secret values stay masked (********).',
    operatorHint: '',
  },
  tr: {
    collection: 'Koleksiyon',
    results: 'Sonuçlar',
    cases: 'Testler',
    noCollection: 'Açık koleksiyon yok',
    openShort: 'Aç',
    closeShort: 'Kapat',
    closeCollection: 'Bu koleksiyonu kapat',
    newShort: 'Yeni',
    searchTests: 'Test ara',
    noMatches: 'Eşleşen yok.',
    empty: 'Henüz test yok.',
    notRun: 'Henüz çalıştırılmadı',
    back: 'Geri',
    copied: 'Panoya kopyalandı',
    folderMissing: 'Bu klasörde artık koleksiyon yok.',
    discardConfirm: 'Kaydedilmemiş değişiklikler var. Vazgeçilsin mi?',
    unsavedChanges: 'Kaydedilmemiş değişiklikler',
    discard: 'Vazgeç',
    saveChanges: 'Değişiklikleri kaydet',
    saved: 'Kaydedildi',
    deleted: 'Silindi',
    sharedTab: 'Ortak adımlar',
    sharedSteps: 'Ortak adımlar',
    sharedBadge: 'ORTAK',
    newShared: 'Yeni ortak adımlar',
    noSharedTitle: 'Henüz ortak adım yok',
    noSharedDescription:
      'Birçok testin önce ihtiyaç duyduğu adımlar (yetki jetonu almak, veritabanından bir kimlik okumak gibi) burada bir kez yazılıp yeniden kullanılabilir.',
    sharedHint:
      'Ortak bir grubu herhangi bir teste “Ortak adımları kullan” ile ekleyin. Kaydettiği değişkenler sonraki adımlarda kullanılabilir.',
    sharedNamePlaceholder: 'Bu ortak adımlara ad verin, örn. Yetki jetonu al',
    nameRequiredShared: 'Kaydetmeden önce ad gerekli.',
    sharedFileHint: 'Testler bu dosyaya başvurduğu için dosya adı sabit kalır.',
    sharedStepButton: 'Ortak adımları kullan',
    sharedStepButtonHint: 'Önce bir grup ortak adım çalıştır',
    noSharedYet: 'Önce ortak adımlar oluşturun (Koleksiyon → Ortak adımlar)',
    chooseShared: 'Ortak adımları seçin…',
    sharedMissing: 'Bu ortak adımlar artık yok.',
    stepsShort: 'adım',
    stepOne: 'adım',
    runMode: 'Ne zaman çalışsın',
    runsOnce: 'Çalıştırmada bir kez',
    runsEach: 'Her testte',
    runsOnceHint:
      'Çalıştırma başına yalnızca bir kez çalışır (örneğin tüm testler için tek giriş). Sonucu yeniden kullanılır ve bir testin kendi değişkenlerine bağlı olamaz.',
    runsEachHint: 'Kullanan her testin içinde, o testin değişkenleriyle yeniden çalışır.',
    providesHint: 'Bu adımların kaydettiği bir değişken',
    run: 'Tümünü çalıştır',
    welcomeTitle: 'Kod yazmadan API testleri',
    welcomeSub:
      'İstekleri ve kontrolleri görsel oluşturucuda tanımlayın. Her şey Git’te saklayıp CI’da çalıştırabileceğiniz okunabilir dosyalardır.',
    open: 'Koleksiyon aç',
    openDescription: 'İçinde koleksiyon bulunan bir klasör seçin.',
    createNew: 'Yeni koleksiyon',
    emptyCollectionDescription: 'Sıfırdan başlayın, testleri sonra ekleyin.',
    importOpenApi: 'OpenAPI içe aktar',
    importOpenApiShort: 'Bir API’nin her endpoint’i için başlangıç testi oluşturun.',
    recent: 'Son koleksiyonlar',
    folderWithoutCollection: 'Bu klasörde henüz koleksiyon yok.',
    createHere: 'Koleksiyonu burada oluştur',
    setupTitle: 'Yeni koleksiyon',
    setupSub:
      'Koleksiyon; testlerden ve ortak değişken, bağlantı ve gizli değerlerden oluşan bir klasördür.',
    chooseFolderHint: 'Nereye kaydedileceğini sonraki adımda seçeceksiniz.',
    emptyCollectionTitle: 'Boş koleksiyon',
    importOpenApiTitle: 'OpenAPI’den içe aktar',
    importOpenApiDescription: 'Swagger / OpenAPI belge adresi',
    overviewTitle: 'Koleksiyon',
    overviewSub: 'Testleri ve paylaştıkları değişken, bağlantı ve gizli değerleri yönetin.',
    newCase: 'Yeni test',
    globals: 'Değişkenler',
    connections: 'Bağlantılar',
    secrets: 'Gizli değerler',
    noTestsTitle: 'Henüz test yok',
    noTestsDescription:
      'İlk testinizi oluşturun veya bir OpenAPI belgesinden her endpoint için test içe aktarın.',
    variablesHint:
      'Değişkeni her yerde {{ad}} olarak kullanın. Adlar yalnızca harf ve alt çizgi içerebilir.',
    noVariablesTitle: 'Değişken yok',
    noVariablesDescription: 'Değişkenler, temel adres gibi değerleri tek yerde tutar.',
    connectionsHint:
      'SQL adımlarının kullandığı veritabanı bağlantıları. Parolaları gizli değerlerde tutun: {{secret.ad}}.',
    noConnectionsTitle: 'Bağlantı yok',
    noConnectionsDescription: 'SQL adımlarını çalıştırmak için bir veritabanı bağlantısı ekleyin.',
    noSecretsTitle: 'Gizli değer yok',
    noSecretsDescription: 'Gizli değerler parola ve token’ları dosyalarınızın dışında tutar.',
    addVariable: 'Değişken ekle',
    addConnection: 'Bağlantı ekle',
    addSecret: 'Gizli değer ekle',
    name: 'Ad',
    value: 'Değer',
    provider: 'Sağlayıcı',
    connectionString: 'Bağlantı dizesi',
    remove: 'Sil',
    secretsHint:
      'Bir gizli değere her yerden {{secret.ad}} ile başvurun. Koleksiyon dosyasına yalnızca nereden geldiği yazılır, değer asla yazılmaz.',
    environmentHint:
      'Ortama özel kaynak, Çalıştır’ın yanında o ortam seçildiğinde varsayılan kaynağın yerine geçer.',
    secretName: 'ad',
    secretDefaultSource: 'Varsayılan kaynak',
    secretLocalNote: 'Değer bu makinede saklanır',
    secretValue: 'Değeri girin (yalnızca yazılır)',
    secretStored: 'Güvenle saklandı',
    secretSetValue: 'Değeri kaydet',
    secretKeyPlaceholder: 'anahtar',
    copySnippet: 'Başvuruyu kopyala',
    addEnvironment: 'Ortama özel kaynak ekle',
    environmentName: 'ortam, örn. ci',
    environment: 'Ortam',
    environmentDefault: 'varsayılan',
    testNamePlaceholder: 'Teste bir ad verin',
    descriptionPlaceholder: 'Kısa bir açıklama ekleyin (isteğe bağlı)',
    testName: 'Test adı',
    description: 'Açıklama',
    endpoint: 'Endpoint',
    endpointHint: 'Bu testi kenar çubuğunda ve sonuçlarda gruplamak için kullanılır.',
    fileHint: 'Dosyayı kendiniz yeniden adlandırmadıysanız dosya adı test adını otomatik izler.',
    newFileHint: 'Dosya adı, kaydettiğinizde test adından seçilir.',
    nameAndEndpointRequired: 'Kaydetmeden önce ad ve endpoint gerekli.',
    method: 'Yöntem',
    steps: 'Adımlar',
    expandAll: 'Tümünü aç',
    collapseAll: 'Tümünü kapat',
    noSteps: 'Başlamak için bir istek veya SQL adımı ekleyin.',
    requestStep: 'İstek adımı',
    dbStep: 'Veritabanı adımı',
    untitledStep: 'Adsız adım',
    moveUp: 'Yukarı taşı',
    moveDown: 'Aşağı taşı',
    delete: 'Sil',
    saveTest: 'Testi kaydet',
    saveAs: 'Sonucu şu adla sakla',
    saveAsHint: 'İsteğe bağlı. Sonucu sonraki adımlarda kullanın.',
    resultName: 'todo',
    url: 'Adres',
    queryParamsShort: 'Parametreler',
    headersShort: 'Başlıklar',
    bodyShort: 'Gövde',
    addQueryParameter: 'Parametre ekle',
    addHeader: 'Başlık ekle',
    connection: 'Bağlantı',
    chooseConnection: 'Bağlantı seçin…',
    noConnectionsYet: 'Önce koleksiyona bağlantı ekleyin',
    sql: 'SQL sorgusu',
    assertions: 'Doğrulamalar',
    noAssertions: 'Henüz doğrulama yok. Yanıtı kontrol etmek için ekleyin.',
    addAssertion: 'Doğrulama ekle',
    assertionCheck: 'Kontrol',
    assertionValue: 'status, body.items.0.name …',
    sourceResult: 'adım sonucu',
    sourceSaved: 'kaydedilen sonuç',
    sourceVariable: 'değişken',
    aggregation: 'Toplulaştırma',
    aggregationNone: 'yok',
    aggregationHint:
      'Değerin kendisi yerine hesaplanan bir değeri karşılaştırır: öğe sayısı veya sayıların toplamı / ortalaması / en küçüğü / en büyüğü. Her öğeden bir alan toplamak için yolda * kullanın, örn. body.items.*.price',
    operator: 'Operatör',
    expected: 'Beklenen',
    operatorLabels: {
      '==': '= eşittir',
      '!=': '≠ eşit değildir',
      '>': '> büyüktür',
      '>=': '≥ en az',
      '<': '< küçüktür',
      '<=': '≤ en fazla',
      approx: '≈ yaklaşık eşittir',
      contains: 'içerir',
      not_contains: 'içermez',
      starts_with: 'ile başlar',
      ends_with: 'ile biter',
      matches: 'regex ile uyar',
      in: 'şunlardan biridir',
      not_in: 'şunlardan biri değildir',
      exists: 'değeri vardır',
      not_exists: 'değeri yoktur',
      is_null: 'null’dır',
      is_missing: 'hiç yoktur',
      is_empty: 'boştur',
      is_not_empty: 'boş değildir',
      is_type: 'türü şudur',
    },
    opGroupCompare: 'Karşılaştırma',
    opGroupText: 'Metin',
    opGroupList: 'Liste',
    opGroupPresence: 'Varlık ve tür',
    valueTypes: {
      string: 'metin',
      number: 'sayı',
      boolean: 'doğru / yanlış',
      array: 'liste',
      object: 'nesne',
      null: 'null',
    },
    expectedListPlaceholder: '200, 201, 204',
    expectedRegexPlaceholder: '^[0-9a-f]{8}$',
    assertionOptions: 'Karşılaştırma seçenekleri',
    caseSensitive: 'Büyük/küçük harf duyarlı',
    caseSensitiveHint:
      'Metin karşılaştırmalarında büyük ve küçük harfi ayırt eder (varsayılan: yok sayar).',
    strictTypes: 'Katı türler',
    strictTypesHint: 'Tür dönüşümü yapılmaz: "200" metni 200 sayısına eşit değildir.',
    tolerance: 'Tolerans ±',
    yaml: 'Oluşturulan YAML',
    running: 'Testler çalışıyor…',
    runningSub: 'İstekler ve sorgular yürütülüyor.',
    noRunTitle: 'Henüz sonuç yok',
    noRun:
      'Nelerin geçtiğini ve bir şeyin neden başarısız olduğunu görmek için koleksiyonu çalıştırın.',
    runAgain: 'Tekrar çalıştır',
    runFailedTitle: 'Çalıştırma başlatılamadı',
    allPassed: 'Tüm testler geçti',
    someErrors: '{total} testten {errors} tanesi değerlendirilemedi',
    failedAndErrors: '{failed} başarısız, {errors} değerlendirilemedi',
    couldNotEvaluate: 'Bu kontrol değerlendirilemedi',
    couldNotEvaluatePlural: 'Değerlendirilemedi',
    stepCouldNotRun: 'Bu adım çalıştırılamadı',
    errorsShort: 'Hatalar',
    errorsHint:
      'Bunlar başarısız kontroller değil, testin kendisindeki sorunlardır (operatör veya kaynakta yazım hatası, çözülemeyen değişken, ulaşılamayan sunucu).',
    someFailed: '{total} testten {failed} tanesi başarısız',
    total: 'Toplam',
    passed: 'Başarılı',
    failed: 'Başarısız',
    success: 'Başarı oranı',
    testResults: 'Test sonuçları',
    filter: 'Sonuçları süz',
    filterAll: 'Tümü',
    expectedLabel: 'Beklenen',
    actualLabel: 'Gerçekleşen',
    status: 'Durum',
    rows: 'satır',
    raw: 'Ham rapor',
    noOutput: 'Çıktı yok.',
    emptyOutput: 'Hiç test çalıştırılmadı.',
    operatorHint: '',
    runTest: 'Bu testi çalıştır',
    runTestSaveFirst: 'Önce testi kaydedin',
    runFailedAgain: 'Başarısızları tekrar çalıştır',
    cancelRun: 'İptal',
    progressCount: '{total} testten {done} tanesi tamamlandı',
    runCancelled: 'Çalıştırma iptal edildi',
    runCancelledSub: 'İptal edilmeden önce {total} testten {done} tanesi tamamlandı.',
    ranSubset: 'Koleksiyonun {count} testi çalıştırıldı',
    send: 'Gönder',
    sendHint: 'Bu adıma kadar olan adımları çalıştırır ve bu adımın aldığı yanıtı gösterir',
    sending: 'Gönderiliyor…',
    response: 'Yanıt',
    responseHeaders: 'Başlıklar',
    responseTruncated: 'Yanıt uzun; yalnızca başı gösteriliyor.',
    rowsShown: '{total} satırdan {shown} tanesi gösteriliyor',
    clickToAssert: 'Kontrol eklemek için bir değere tıklayın.',
    countCheck: 'Sayı kontrolü ekle',
    stoppedEarlier: 'Bu adıma gelmeden {step}. adımda ({name}) durdu.',
    noResponse: 'Bu adım bir yanıt almadı.',
    closePreview: 'Kapat',
    bodyNotJson:
      'Bu gövde geçerli bir JSON değil ({error}); bu yüzden text/plain olarak gönderilir. JSON’da anahtarlar ve metinler çift tırnak içinde olmalıdır: {"title": "foo"}.',
    bodyNotJsonDeclared:
      'Bu gövde geçerli bir JSON değil ({error}), ancak Content-Type başlığı JSON diyor; sunucu büyük olasılıkla reddedecektir. JSON’da anahtarlar ve metinler çift tırnak içinde olmalıdır: {"title": "foo"}.',
    cloneTest: 'Kopyala',
    cloneTestHint:
      'Bu testin bir kopyasını oluşturur; bir varyasyon için başlangıç noktası olarak kullanın',
    cloned: 'Test kopyalandı',
    copyName: '{name} (kopya)',
    copyNameN: '{name} (kopya {n})',
    sentRequest: 'Gönderilen istek',
    sentSql: 'Çalıştırılan SQL',
    noRequestBody: 'Gövde gönderilmedi.',
    copyCurl: 'cURL olarak kopyala',
    copyCurlHint: 'İsteği curl komutu olarak kopyalar. Gizli değerler maskeli (********) kalır.',
  },
};
