// UI copy added or reworded by the redesign; merged over the base translations in i18n.js.
export const strings = {
  en: {
    // shell
    collection: 'Collection',
    results: 'Results',
    cases: 'Tests',
    noCollection: 'No collection open',
    openShort: 'Open',
    newShort: 'New',
    searchTests: 'Search tests',
    noMatches: 'Nothing matches.',
    empty: 'No tests yet.',
    notRun: 'Not run yet',
    back: 'Back',
    copied: 'Copied to clipboard',
    folderMissing: 'That folder no longer contains a collection.',
    discardConfirm: 'You have unsaved changes. Discard them?',
    unsavedChanges: 'Unsaved changes',
    discard: 'Discard',
    saveChanges: 'Save changes',
    saved: 'Saved',
    deleted: 'Test deleted',
    run: 'Run all',
    // welcome & setup
    welcomeTitle: 'API tests, without the code',
    welcomeSub:
      'Describe requests and checks in a visual builder. Everything is stored as readable files you can keep in Git and run in CI.',
    open: 'Open collection',
    openDescription: 'Pick a folder that already contains a collection.',
    createNew: 'New collection',
    emptyCollectionDescription: 'Start from scratch and add tests as you go.',
    importOpenApi: 'Import OpenAPI',
    importOpenApiShort: 'Generate a starter test for every endpoint of an API.',
    recent: 'Recent collections',
    folderWithoutCollection: 'This folder has no collection yet.',
    createHere: 'Create collection here',
    setupTitle: 'New collection',
    setupSub: 'A collection is a folder of tests plus shared variables, connections and secrets.',
    chooseFolderHint: 'You will choose where to save it next.',
    emptyCollectionTitle: 'Empty collection',
    importOpenApiTitle: 'Import from OpenAPI',
    importOpenApiDescription: 'Swagger / OpenAPI document URL',
    // collection page
    overviewTitle: 'Collection',
    overviewSub: 'Manage tests and the variables, connections and secrets they share.',
    newCase: 'New test',
    globals: 'Variables',
    connections: 'Connections',
    secrets: 'Secrets',
    noTestsTitle: 'No tests yet',
    noTestsDescription:
      'Create your first test, or import one for every endpoint from an OpenAPI document.',
    variablesHint:
      'Use a variable anywhere as {{name}}. Names may contain letters and underscores only.',
    noVariablesTitle: 'No variables',
    noVariablesDescription: 'Variables keep values such as base URLs in one place.',
    connectionsHint:
      'Database connections used by SQL steps. Put passwords in secrets: {{secret.name}}.',
    noConnectionsTitle: 'No connections',
    noConnectionsDescription: 'Add a database connection to run SQL steps.',
    noSecretsTitle: 'No secrets',
    noSecretsDescription: 'Secrets keep passwords and tokens out of your files.',
    addVariable: 'Add variable',
    addConnection: 'Add connection',
    addSecret: 'Add secret',
    name: 'Name',
    value: 'Value',
    provider: 'Provider',
    connectionString: 'Connection string',
    remove: 'Remove',
    secretsHint:
      'Reference a secret anywhere as {{secret.name}}. Only where it comes from is saved in the collection file, never the value.',
    environmentHint:
      'An environment override replaces the default source when that environment is selected next to Run.',
    secretName: 'name',
    secretDefaultSource: 'Default source',
    secretLocalNote: 'Value is stored on this machine',
    secretValue: 'Enter value (write-only)',
    secretStored: 'Stored securely',
    secretSetValue: 'Save value',
    secretKeyPlaceholder: 'key',
    copySnippet: 'Copy reference',
    addEnvironment: 'Add environment override',
    environmentName: 'environment, e.g. ci',
    environment: 'Environment',
    environmentDefault: 'default',
    // builder
    testNamePlaceholder: 'Name this test',
    descriptionPlaceholder: 'Add a short description (optional)',
    testName: 'Test name',
    description: 'Description',
    endpoint: 'Endpoint',
    endpointHint: 'Used to group this test in the sidebar and in results.',
    nameAndEndpointRequired: 'A name and an endpoint are needed before saving.',
    method: 'Method',
    steps: 'Steps',
    expandAll: 'Expand all',
    collapseAll: 'Collapse all',
    noSteps: 'Add a request or SQL step to get started.',
    requestStep: 'Request step',
    dbStep: 'Database step',
    untitledStep: 'Untitled step',
    moveUp: 'Move up',
    moveDown: 'Move down',
    delete: 'Delete',
    saveTest: 'Save test',
    saveAs: 'Save result as',
    saveAsHint: 'Optional. Use the result in later steps.',
    resultName: 'todo',
    url: 'URL',
    queryParamsShort: 'Params',
    headersShort: 'Headers',
    bodyShort: 'Body',
    addQueryParameter: 'Add parameter',
    addHeader: 'Add header',
    connection: 'Connection',
    chooseConnection: 'Choose a connection…',
    noConnectionsYet: 'Add connections in the collection first',
    sql: 'SQL query',
    assertions: 'Assertions',
    noAssertions: 'No assertions yet. Add one to check the response.',
    addAssertion: 'Add assertion',
    assertionCheck: 'Check',
    assertionValue: 'status, body.items.0.name …',
    sourceResult: 'step result',
    sourceSaved: 'saved result',
    sourceVariable: 'variable',
    aggregation: 'Aggregation',
    aggregationNone: 'none',
    aggregationHint:
      'Compare a computed value instead of the value itself: count of items, or sum / avg / min / max of numbers. Use * in the path to collect a field from every item, e.g. body.items.*.price',
    operator: 'Operator',
    expected: 'Expected',
    operatorLabels: {
      '==': '= equals',
      '!=': '≠ not equals',
      '>': '> greater than',
      '>=': '≥ at least',
      '<': '< less than',
      '<=': '≤ at most',
      contains: 'contains',
      not_contains: 'does not contain',
      exists: 'exists',
      not_exists: 'does not exist',
    },
    yaml: 'Generated YAML',
    // results
    running: 'Running tests…',
    runningSub: 'Requests and queries are being executed.',
    noRunTitle: 'No results yet',
    noRun: 'Run the collection to see what passed and why something failed.',
    runAgain: 'Run again',
    runFailedTitle: 'The run could not start',
    allPassed: 'All tests passed',
    someFailed: '{failed} of {total} tests failed',
    total: 'Total',
    passed: 'Passed',
    failed: 'Failed',
    success: 'Success rate',
    testResults: 'Test results',
    filter: 'Filter results',
    filterAll: 'All',
    expectedLabel: 'Expected',
    actualLabel: 'Actual',
    status: 'Status',
    rows: 'rows',
    raw: 'Raw report',
    noOutput: 'No output.',
    emptyOutput: 'No tests were run.',
    operatorHint: '',
  },
  tr: {
    collection: 'Koleksiyon',
    results: 'Sonuçlar',
    cases: 'Testler',
    noCollection: 'Açık koleksiyon yok',
    openShort: 'Aç',
    newShort: 'Yeni',
    searchTests: 'Test ara',
    noMatches: 'Eşleşen yok.',
    empty: 'Henüz test yok.',
    notRun: 'Henüz çalıştırılmadı',
    back: 'Geri',
    copied: 'Panoya kopyalandı',
    folderMissing: 'Bu klasörde artık koleksiyon yok.',
    discardConfirm: 'Kaydedilmemiş değişiklikler var. Vazgeçilsin mi?',
    unsavedChanges: 'Kaydedilmemiş değişiklikler',
    discard: 'Vazgeç',
    saveChanges: 'Değişiklikleri kaydet',
    saved: 'Kaydedildi',
    deleted: 'Test silindi',
    run: 'Tümünü çalıştır',
    welcomeTitle: 'Kod yazmadan API testleri',
    welcomeSub:
      'İstekleri ve kontrolleri görsel oluşturucuda tanımlayın. Her şey Git’te saklayıp CI’da çalıştırabileceğiniz okunabilir dosyalardır.',
    open: 'Koleksiyon aç',
    openDescription: 'İçinde koleksiyon bulunan bir klasör seçin.',
    createNew: 'Yeni koleksiyon',
    emptyCollectionDescription: 'Sıfırdan başlayın, testleri sonra ekleyin.',
    importOpenApi: 'OpenAPI içe aktar',
    importOpenApiShort: 'Bir API’nin her endpoint’i için başlangıç testi oluşturun.',
    recent: 'Son koleksiyonlar',
    folderWithoutCollection: 'Bu klasörde henüz koleksiyon yok.',
    createHere: 'Koleksiyonu burada oluştur',
    setupTitle: 'Yeni koleksiyon',
    setupSub:
      'Koleksiyon; testlerden ve ortak değişken, bağlantı ve gizli değerlerden oluşan bir klasördür.',
    chooseFolderHint: 'Nereye kaydedileceğini sonraki adımda seçeceksiniz.',
    emptyCollectionTitle: 'Boş koleksiyon',
    importOpenApiTitle: 'OpenAPI’den içe aktar',
    importOpenApiDescription: 'Swagger / OpenAPI belge adresi',
    overviewTitle: 'Koleksiyon',
    overviewSub: 'Testleri ve paylaştıkları değişken, bağlantı ve gizli değerleri yönetin.',
    newCase: 'Yeni test',
    globals: 'Değişkenler',
    connections: 'Bağlantılar',
    secrets: 'Gizli değerler',
    noTestsTitle: 'Henüz test yok',
    noTestsDescription:
      'İlk testinizi oluşturun veya bir OpenAPI belgesinden her endpoint için test içe aktarın.',
    variablesHint:
      'Değişkeni her yerde {{ad}} olarak kullanın. Adlar yalnızca harf ve alt çizgi içerebilir.',
    noVariablesTitle: 'Değişken yok',
    noVariablesDescription: 'Değişkenler, temel adres gibi değerleri tek yerde tutar.',
    connectionsHint:
      'SQL adımlarının kullandığı veritabanı bağlantıları. Parolaları gizli değerlerde tutun: {{secret.ad}}.',
    noConnectionsTitle: 'Bağlantı yok',
    noConnectionsDescription: 'SQL adımlarını çalıştırmak için bir veritabanı bağlantısı ekleyin.',
    noSecretsTitle: 'Gizli değer yok',
    noSecretsDescription: 'Gizli değerler parola ve token’ları dosyalarınızın dışında tutar.',
    addVariable: 'Değişken ekle',
    addConnection: 'Bağlantı ekle',
    addSecret: 'Gizli değer ekle',
    name: 'Ad',
    value: 'Değer',
    provider: 'Sağlayıcı',
    connectionString: 'Bağlantı dizesi',
    remove: 'Sil',
    secretsHint:
      'Bir gizli değere her yerden {{secret.ad}} ile başvurun. Koleksiyon dosyasına yalnızca nereden geldiği yazılır, değer asla yazılmaz.',
    environmentHint:
      'Ortama özel kaynak, Çalıştır’ın yanında o ortam seçildiğinde varsayılan kaynağın yerine geçer.',
    secretName: 'ad',
    secretDefaultSource: 'Varsayılan kaynak',
    secretLocalNote: 'Değer bu makinede saklanır',
    secretValue: 'Değeri girin (yalnızca yazılır)',
    secretStored: 'Güvenle saklandı',
    secretSetValue: 'Değeri kaydet',
    secretKeyPlaceholder: 'anahtar',
    copySnippet: 'Başvuruyu kopyala',
    addEnvironment: 'Ortama özel kaynak ekle',
    environmentName: 'ortam, örn. ci',
    environment: 'Ortam',
    environmentDefault: 'varsayılan',
    testNamePlaceholder: 'Teste bir ad verin',
    descriptionPlaceholder: 'Kısa bir açıklama ekleyin (isteğe bağlı)',
    testName: 'Test adı',
    description: 'Açıklama',
    endpoint: 'Endpoint',
    endpointHint: 'Bu testi kenar çubuğunda ve sonuçlarda gruplamak için kullanılır.',
    nameAndEndpointRequired: 'Kaydetmeden önce ad ve endpoint gerekli.',
    method: 'Yöntem',
    steps: 'Adımlar',
    expandAll: 'Tümünü aç',
    collapseAll: 'Tümünü kapat',
    noSteps: 'Başlamak için bir istek veya SQL adımı ekleyin.',
    requestStep: 'İstek adımı',
    dbStep: 'Veritabanı adımı',
    untitledStep: 'Adsız adım',
    moveUp: 'Yukarı taşı',
    moveDown: 'Aşağı taşı',
    delete: 'Sil',
    saveTest: 'Testi kaydet',
    saveAs: 'Sonucu şu adla sakla',
    saveAsHint: 'İsteğe bağlı. Sonucu sonraki adımlarda kullanın.',
    resultName: 'todo',
    url: 'Adres',
    queryParamsShort: 'Parametreler',
    headersShort: 'Başlıklar',
    bodyShort: 'Gövde',
    addQueryParameter: 'Parametre ekle',
    addHeader: 'Başlık ekle',
    connection: 'Bağlantı',
    chooseConnection: 'Bağlantı seçin…',
    noConnectionsYet: 'Önce koleksiyona bağlantı ekleyin',
    sql: 'SQL sorgusu',
    assertions: 'Doğrulamalar',
    noAssertions: 'Henüz doğrulama yok. Yanıtı kontrol etmek için ekleyin.',
    addAssertion: 'Doğrulama ekle',
    assertionCheck: 'Kontrol',
    assertionValue: 'status, body.items.0.name …',
    sourceResult: 'adım sonucu',
    sourceSaved: 'kaydedilen sonuç',
    sourceVariable: 'değişken',
    aggregation: 'Toplulaştırma',
    aggregationNone: 'yok',
    aggregationHint:
      'Değerin kendisi yerine hesaplanan bir değeri karşılaştırır: öğe sayısı veya sayıların toplamı / ortalaması / en küçüğü / en büyüğü. Her öğeden bir alan toplamak için yolda * kullanın, örn. body.items.*.price',
    operator: 'Operatör',
    expected: 'Beklenen',
    operatorLabels: {
      '==': '= eşittir',
      '!=': '≠ eşit değildir',
      '>': '> büyüktür',
      '>=': '≥ en az',
      '<': '< küçüktür',
      '<=': '≤ en fazla',
      contains: 'içerir',
      not_contains: 'içermez',
      exists: 'vardır',
      not_exists: 'yoktur',
    },
    yaml: 'Oluşturulan YAML',
    running: 'Testler çalışıyor…',
    runningSub: 'İstekler ve sorgular yürütülüyor.',
    noRunTitle: 'Henüz sonuç yok',
    noRun:
      'Nelerin geçtiğini ve bir şeyin neden başarısız olduğunu görmek için koleksiyonu çalıştırın.',
    runAgain: 'Tekrar çalıştır',
    runFailedTitle: 'Çalıştırma başlatılamadı',
    allPassed: 'Tüm testler geçti',
    someFailed: '{total} testten {failed} tanesi başarısız',
    total: 'Toplam',
    passed: 'Başarılı',
    failed: 'Başarısız',
    success: 'Başarı oranı',
    testResults: 'Test sonuçları',
    filter: 'Sonuçları süz',
    filterAll: 'Tümü',
    expectedLabel: 'Beklenen',
    actualLabel: 'Gerçekleşen',
    status: 'Durum',
    rows: 'satır',
    raw: 'Ham rapor',
    noOutput: 'Çıktı yok.',
    emptyOutput: 'Hiç test çalıştırılmadı.',
    operatorHint: '',
  },
};
